import uuid
from datetime import date,datetime
from decimal import Decimal
from sqlalchemy import Date,DateTime,ForeignKey,Numeric,String,Text,func
from sqlalchemy.orm import Mapped,mapped_column
from app.database.session import Base
class Invoice(Base):
 __tablename__='invoices'
 id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4);user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id'),index=True);shift_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('shifts.id'),index=True);contractor_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('contractors.id'),index=True);number:Mapped[str]=mapped_column(String(60));series:Mapped[str|None]=mapped_column(String(30));verification_code:Mapped[str|None]=mapped_column(String(100));municipality:Mapped[str|None]=mapped_column(String(100));provider:Mapped[str|None]=mapped_column(String(160));customer:Mapped[str|None]=mapped_column(String(160));issue_date:Mapped[date|None]=mapped_column(Date);competence:Mapped[date]=mapped_column(Date);service_value:Mapped[Decimal]=mapped_column(Numeric(12,2));net_value:Mapped[Decimal|None]=mapped_column(Numeric(12,2));rate:Mapped[Decimal|None]=mapped_column(Numeric(6,3));iss:Mapped[Decimal|None]=mapped_column(Numeric(12,2));ir:Mapped[Decimal|None]=mapped_column(Numeric(12,2));pis:Mapped[Decimal|None]=mapped_column(Numeric(12,2));cofins:Mapped[Decimal|None]=mapped_column(Numeric(12,2));csll:Mapped[Decimal|None]=mapped_column(Numeric(12,2));inss:Mapped[Decimal|None]=mapped_column(Numeric(12,2));status:Mapped[str]=mapped_column(String(30),default='Pendente');pdf_url:Mapped[str|None]=mapped_column(String(500));xml_url:Mapped[str|None]=mapped_column(String(500));notes:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now());updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now());deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
