"""add intelligent expenses"""
from alembic import op
import sqlalchemy as sa
revision='0008_expenses';down_revision='0007_cashflow_projection';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('expense_categories',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id'),nullable=False),sa.Column('nome',sa.String(80),nullable=False),sa.Column('cor',sa.String(20),nullable=False),sa.Column('ativa',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('deleted_at',sa.DateTime(timezone=True)));op.create_index('ix_expense_categories_user_id','expense_categories',['user_id'])
 op.create_table('expenses',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id'),nullable=False),sa.Column('titulo',sa.String(160),nullable=False),sa.Column('descricao',sa.Text()),sa.Column('categoria_id',sa.Uuid(),sa.ForeignKey('expense_categories.id'),nullable=False),sa.Column('valor',sa.Numeric(12,2),nullable=False),sa.Column('tipo',sa.String(20),nullable=False),sa.Column('forma_pagamento',sa.String(20),nullable=False),sa.Column('fornecedor',sa.String(160)),sa.Column('competencia',sa.Date(),nullable=False),sa.Column('data_vencimento',sa.Date(),nullable=False),sa.Column('data_pagamento',sa.Date()),sa.Column('status',sa.String(20),nullable=False),sa.Column('recorrente',sa.Boolean(),nullable=False),sa.Column('intervalo_recorrencia',sa.String(20)),sa.Column('recurrence_parent_id',sa.Uuid(),sa.ForeignKey('expenses.id')),sa.Column('centro_custo',sa.String(60)),sa.Column('observacoes',sa.Text()),sa.Column('comprovante_url',sa.String(500)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('deleted_at',sa.DateTime(timezone=True)))
 for c in ('user_id','categoria_id','tipo','fornecedor','competencia','data_vencimento','status','recurrence_parent_id'):op.create_index(f'ix_expenses_{c}','expenses',[c])
def downgrade():op.drop_table('expenses');op.drop_table('expense_categories')
