import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Landmark,PiggyBank,ShieldCheck,TrendingUp } from 'lucide-react'
import { Simulator } from '@/components/taxes/Simulator'
import { TaxCard } from '@/components/taxes/TaxCard'
import { TaxChart } from '@/components/taxes/TaxChart'
import { TaxHistory } from '@/components/taxes/TaxHistory'
import { TaxSummary } from '@/components/taxes/TaxSummary'
import { TaxSettingsPanel } from '@/components/taxes/TaxSettingsPanel'
import { taxesService } from '@/services/taxes'
const money=(n=0)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});type Tab='dashboard'|'history'|'simulator'|'settings'
function Skeleton(){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-36 animate-pulse rounded-xl bg-slate-100"/>)}</div>}
export function TaxesPage(){const[tab,setTab]=useState<Tab>('dashboard'),[toast,setToast]=useState('');const dashboard=useQuery({queryKey:['tax-dashboard'],queryFn:taxesService.dashboard,staleTime:60_000}),history=useQuery({queryKey:['tax-history'],queryFn:taxesService.history,staleTime:30_000}),settings=useQuery({queryKey:['tax-settings'],queryFn:taxesService.settings,staleTime:300_000}),d=dashboard.data,tabs:[Tab,string][]=[['dashboard','Dashboard Tributário'],['history','Histórico'],['simulator','Simulador'],['settings','Configurações']];return <div><header className="mb-6"><p className="text-sm font-medium text-blue-600">Inteligência Tributária</p><h1 className="mt-1 text-2xl font-bold">Planejamento da reserva tributária</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Estimativas para organizar receitas PJ; a apuração oficial deve seguir seu contador.</p></header><nav className="mb-6 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{tabs.map(([key,label])=><button type="button" key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-sm font-medium ${tab===key?'bg-blue-600 text-white':'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</nav>{toast&&<div role="status" className="fixed bottom-5 right-5 z-50 rounded-lg bg-emerald-600 px-4 py-3 text-sm text-white">{toast}</div>}{tab==='dashboard'&&(dashboard.isLoading?<Skeleton/>:d&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><TaxCard label="Reserva sugerida do mês" value={money(d.estimated_month)} detail="Planejamento do período atual" icon={Landmark}/><TaxCard label="Total efetivamente reservado" value={money(d.reserved_total)} detail="Marcado como reservado ou pago" icon={ShieldCheck} tone="green"/><TaxCard label="Sugestão ainda não reservada" value={money(d.not_reserved)} detail="Estimativa em aberto" icon={PiggyBank} tone="amber"/><TaxCard label="Disponível após reserva" value={money(d.estimated_net_profit)} detail="Receita PJ menos reserva sugerida" icon={TrendingUp} tone="violet"/></div><TaxSummary coverage={d.coverage} disclaimer={d.disclaimer}/><div className="grid gap-5 xl:grid-cols-[1.4fr_0.6fr]"><TaxChart data={d.series}/><section className="card p-5"><h2 className="font-semibold">Insights</h2>{d.insights.map(x=><p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-600" key={x}>{x}</p>)}</section></div></div>)}{tab==='history'&&(history.isLoading?<Skeleton/>:<TaxHistory items={history.data?.items??[]} onReserved={()=>{setToast('Dinheiro marcado como reservado.');setTimeout(()=>setToast(''),2500)}}/>)}{tab==='simulator'&&(settings.isLoading?<Skeleton/>:<Simulator defaultPercentage={settings.data?.recommended_reserve_percentage??15}/>)}{tab==='settings'&&<TaxSettingsPanel/>}</div>}
